version: "3.8"

services:
  pix-extractor:
    image: jondevsouza31/api-comprovante:latest
    ports:
      - "8080:8000"
    environment:
      - EXPECTED_NOME_RECEBEDOR=Maria Eduarda Cavaton
      - EXPECTED_CPF_RECEBEDOR_PARTIAL=824.458
      - EXPECTED_INSTITUICAO_RECEBEDOR=Banco Inter
      - EXPECTED_CHAVE_PIX=16991500219
      - MAX_HORAS_VALIDADE=24
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
